### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by Kranzes** [fzakaria/nix-auto-follow#1]
This error happens for all of my flakes because duplicate_ref is a list.

```
Traceback (most recent call last):
  File "/home/kranzes/devel/nix-config/all-follow.py", line 54, in <module>
    main()
  File "/home/kranzes/devel/nix-config/all-follow.py", line 44, in main
    modified_data = update_flake_lock(input_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kranzes/devel/nix-config/all-follow.py", line 29, in update_flake_lock
    flake_lock["nodes"][duplicate_ref] = value
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list
```

**Comment by fzakaria** [comment]
Thank you for the bug report; I'll write a proper derivation for this and move my examples to unit tests.
The missing case was if you have already some follows.

**Comment by KenMacD** [comment]
Not sure if this should be it's own bug, but it also fails at:

```
Traceback (most recent call last):
  File ".../all-follow.py", line 58, in <module>
    main()
  File ".../all-follow.py", line 48, in main
    modified_data = update_flake_lock(input_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../all-follow.py", line 19, in update_flake_lock
    value = flake_lock["nodes"][ref]
            ~~~~~~~~~~~~~~~~~~~^^^^^
TypeError: unhashable type: 'list'
```

**Comment by fzakaria** [comment]
@KenMacD can you share your lockfile?

**Comment by fzakaria** [comment]
Ah found it: https://github.com/KenMacD/etc-nixos/blob/main/flake.nix
that shows it thanks.

**Comment by KenMacD** [comment]
Tested the latest version and it worked. Thanks!

**Comment by fzakaria** [comment]
Try out the `--check` command and let me know what you think; happy to take back feedback.
