### ISSUE TITLE
Check crashing

### ISSUE THREAD

**Issue by bestlem** [fzakaria/nix-auto-follow#7]
Note this is on macOS if that matters. I attach my 
[flake.lock.txt](https://github.com/user-attachments/files/16479126/flake.lock.txt)

`nix run github:fzakaria/nix-auto-follow -- -c`

gives
```
Node cachix has input nixpkgs pointing to nixpkgs_2 which is not the same as crate2nix's nixpkgs which is nixpkgs_3 in the lockfile.
Traceback (most recent call last):
  File "/nix/store/9aqpdql9cwmsvmdd4m33cnxl9nw6z6xc-nix-auto-follow/bin/.auto-follow-wrapped", line 9, in <module>
    sys.exit(start())
             ^^^^^^^
  File "/nix/store/9aqpdql9cwmsvmdd4m33cnxl9nw6z6xc-nix-auto-follow/lib/python3.12/site-packages/nix_auto_follow/cli.py", line 189, in start
    if not check_lock_file(LockFile.from_dict(flake_lock_json)):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/9aqpdql9cwmsvmdd4m33cnxl9nw6z6xc-nix-auto-follow/lib/python3.12/site-packages/nix_auto_follow/cli.py", line 101, in check_lock_file
    f"Please add '{key}.url = \"{flake_lock.nodes[ref].get_url()}\"' or '{other_key}.url = \"{flake_lock.nodes[other_ref].get_url()}'"  # noqa: E501
                                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/9aqpdql9cwmsvmdd4m33cnxl9nw6z6xc-nix-auto-follow/lib/python3.12/site-packages/nix_auto_follow/cli.py", line 45, in get_url
    raise ValueError(f"Unknown type {original['type']}")
ValueError: Unknown type indirect
```

**Comment by fzakaria** [comment]
Great! Thanks for you filing the issue and trying out nix-auto-follow.
I found the bug and have a fix incoming :)

**Comment by fzakaria** [comment]
```console
❯ auto-follow -c ~/Downloads/flake.lock.txt 
Node cachix has input nixpkgs pointing to nixpkgs_2 which is not the same as crate2nix's nixpkgs which is nixpkgs_3 in the lockfile.
Please add 'nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable"' or 'nixpkgs.url = "nixpkgs'
```
